In [1]:
import numpy as np

In [2]:
import time
import sys

In [17]:
li=range(1000)
print(sys.getsizeof(5)*len(li))
sys.getsizeof(5)

28000


28

In [18]:
arr=np.arange(1000)
print(arr.size*arr.itemsize)
arr.size,arr.itemsize

4000


(1000, 4)

In [24]:
arrlen=10000000
l1=range(arrlen)
l2=range(arrlen)
a1=np.arange(arrlen)
a2=np.arange(arrlen)

In [25]:
start=time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Time :",(time.time()-start)*1000)


Time : 1225.879192352295


In [26]:
start=time.time()
result = a1+a2
print("Time :",(time.time()-start)*1000)

Time : 204.17070388793945


In [27]:
a1+a2

array([       0,        2,        4, ..., 19999994, 19999996, 19999998])

In [28]:
a2-a1

array([0, 0, 0, ..., 0, 0, 0])

In [29]:
a1*a2

array([        0,         1,         4, ..., 216447241, 236447236,
       256447233])

In [33]:
res=a2/a1
print(type(res[0]))
res

<class 'numpy.float64'>


C:\Users\gokul\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1., ...,  1.,  1.,  1.])

In [35]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim # no. of dimensions


2

In [37]:
a.size,a.shape

(6, (3, 2))

In [38]:
a.itemsize

4

In [39]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a.itemsize

8

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [45]:
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [46]:
np.linspace(1,5,num=20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [48]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [50]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [51]:
a.ravel()

array([1., 2., 3., 4., 5., 6.])

In [52]:
a.min(),a.max(),a.sum()

(1.0, 6.0, 21.0)

In [53]:
# axis 0 columns
# axis 1 rows
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[ 9. 12.]
[ 3.  7. 11.]


In [54]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [55]:
np.std(a)

1.707825127659933

In [56]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [62]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [63]:
a+b

array([[ 7.,  9.],
       [11., 13.],
       [15., 17.]])

In [70]:
print(a)
print(b.reshape(2,3))

print(a.dot(b.reshape(2,3)))

a.dot(b)


[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 24.  27.  30.]
 [ 54.  61.  68.]
 [ 84.  95. 106.]]


ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

### 3. numpy tutorial - slicing/stacking arrays, indexing with boolean arrays

In [71]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [75]:
a[2,1]

6.0

In [78]:
a[0:2,1]

array([2., 4.])

In [80]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
a[-1,0:2]

array([6, 7])

In [86]:
a[:,1:3]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [87]:
for row in a:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [92]:
for row in a:
    for col in row:
        print(col)

0
1
2
3
4
5
6
7
8


In [94]:
for cell in a.flat:
    print(cell)


0
1
2
3
4
5
6
7
8


In [95]:

for cell in a.ravel():
    print(cell)    

0
1
2
3
4
5
6
7
8


In [98]:
b=np.arange(10,19).reshape(3,3)

In [99]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [100]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [101]:
np.hstack((a,b))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [102]:
b1=np.arange(30).reshape(2,15)
b1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [104]:
np.hsplit(b1,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [106]:
np.vsplit(b1,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [107]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [110]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [111]:
a[b]=100

In [112]:
a

array([[  0,   1,   2,   3],
       [  4, 100, 100, 100],
       [100, 100, 100, 100]])

In [124]:
#  iterate numpy array using nditer

a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [116]:
for cell in a.flatten():
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [117]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [118]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [120]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [125]:
for x in np.nditer(a,op_flags=['readwrite']):

    x[...]=x*x
a
    

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [126]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [127]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
